### PR TITLE
Comments

### PR DESCRIPTION
**Pull request by fireteam99**
Overhaul of the comment/rating system. Logged out users will now see a disabled button which prevents them from posting comments. Logged in users that have already commented have their comment and rating pre-filled so they can changes it easily.

### CODE REVIEW

**Comment by GatesWang** [comment]
badly written code!

**Comment by fireteam99** [comment]
you don't even know how to write javascript

**Comment by GatesWang** [comment]
@fireteam99  actually i do

**Comment by fireteam99** [comment]
@GatesWang ok buddy

**Pull request closed without merging**
